import React, { useEffect, useState, useContext, useRef } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import NavbarLogout from './navbar-logout'
import NavbarCustom from './navbar-custom'
import NavbarSeller from './navbar-seller'
import Footer from './footer'
import Section from './section'
import Navbars from '../navbars'
import { useSeller } from '../../contexts/SellerContext'
import { useAuth } from '@/contexts/custom-context'
// import { useLoader } from '@/hooks/use-loader'


export default function MainLayout({ children }) {
  
  // const { seller } = useSeller();
  // const sellerId = seller?.id;

  // if(sellerId){
  //   //就渲染賣家
  // }
  const { auth } = useAuth()
  const { seller } = useSeller()
  const sellerId = seller?.id;
  // 根據用戶身份來決定要渲染哪一個導覽列
  const renderNavbar = () => {
    if (auth.custom_id) {
      // 一般會員
      return <NavbarCustom />
    } else if (sellerId) {
      console.log(sellerId)
      // 商家會員
      return <NavbarSeller />
    } else {
      // 未登入或其他情況
      return  <NavbarLogout /> 

    }
  }
  // const { loader } = useLoader()

  return (
    <>
      <Head>
        <title>夜市獵人Nightmarket Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-container-fluid">
        <header className="row">
          {renderNavbar()}
          {/* <NavbarLogout /> */}
          {/* <Navbars /> */}
          {/* <NavbarCustom /> */}
          {/* <NavbarSeller /> */}
        </header>
        <main className="row">
          {children}
          {/* 全域的載入動畫指示器
        {loader()} */}
        </main>
        <Footer />
      </div>
    </>
  )
}
