import React, { useEffect, useState, useContext, useRef } from "react";
import Head from 'next/head'
import Image from 'next/image'
import NavbarLogout from './navbar-logout'
import NavbarCustom from './navbar-custom'
import NavbarSeller from './navbar-seller'
import Footer from './footer'
import Section from './section'
import Navbars from '../navbars'
// import { useSeller } from "../../contexts/SellerContext"

export default function MainLayout({ children }) {


  // const { seller } = useSeller();
  // const sellerId = seller?.id;

  // if(sellerId){
  //   //就渲染賣家
  // }
  return (
    <>
      <Head>
        <title>Nightmarket Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-container-fluid">
        <header className="row">
          {/* <NavbarLogout /> */}
          <Navbars />
          {/* <NavbarCustom /> */}
          {/* <NavbarSeller /> */}
        </header>
        <main className="row">
          {children}
          {/* <div className="section">{children}</div> */}
        </main>
        <Footer />
      </div>
    </>
  )
}
