
GET http://localhost:3001

### request 分隔行

GET http://localhost:3001/try-qs?name=shin&age=32

### request 分隔行

POST http://localhost:3001/try-post

### request 分隔行
POST http://localhost:3001/try-post
Content-Type: application/x-www-form-urlencoded

name=shinder&age=32

### request 分隔行

POST http://localhost:3001/try-post
Content-Type: application/json

{
  "data": [1,2,3],
  "account": "David"
}